
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILURE = 'GET_TODO_FAILURE';


export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const TOGGLE_COMPLETE_TODO_SUCCESS = 'TOGGLE_COMPLETE_TODO_SUCCESS';

export const SHOW_TODO_SUCCESS = 'SHOW_TODO_SUCCESS';

